#!/usr/bin/php
<?php
recurse(".");

function recurse($dir, $lvl = 0) {
    print "####>>>> ".$dir." ".strpos($dir, "search")."\n";
    if (!strpos($dir, "search")) {
        $files = glob("{$dir}/*");

        foreach ($files as $file) {
            if (strpos($file, "search")!==false) {
                continue;
            }
            if (strstr($file, "search")!==true) {
        $searchpath = "./search" . preg_replace("/^\./", '', $file);
        if (is_dir($file) && (!preg_match("/node_modules|backup|archive|adminlte|search/i", $file))) {
            print "--> $file\n";
            if (!file_exists($searchpath)) {
                mkdir($searchpath, 0755, true);
                print "Created folder {$searchpath}\n";
            }
            if (!is_link($file)) {
                if (strpos($file, "search")!==true) {
                    $out = recurse($file, $lvl + 1);
                }
            }
        } else if (preg_match("/\.(html)/", $file, $matches)) {
            $results = `pandoc -f html -t plain $file`;
            $results = preg_replace("/\n\n/", "\n", $results);
            file_put_contents($searchpath, $results);
            print str_repeat("\t", $lvl) . "+ {$file}\n";
        }
            }
    }
    } else {
        print "****** Skipping $dir\n";
    }
}

?>
