#!/usr/local/bin/php
<?php
$exe = array_shift($argv);
$now = date("Ymdhi");

$posts = json_decode(file_get_contents("posts.json"));
$nav = json_decode(file_get_contents("../nav/blog.json"));
print "Backing up current posts.json\n";

$exe = `cp posts.json backup/posts.$now.json`;
$tpl = file_get_contents("blank.html");

$force = 0;
$conf = new stdClass();

while ($file = array_shift($argv)) {
    if (preg_match("/^\-\-([\w\-]+)/", $file, $match)) {
        $conf->{$match[1]} = 1;
        continue;
    } else if (file_exists($file)) {
        $fparts = preg_split("/\./", $file);

        print "Reading markdown from $file...";
        $txt = file_get_contents($file);
        print "Done.\n";

        $para = preg_split("/\n\n/", $txt);     // need for blurb
        $lines = preg_split("/\n/", $txt);      

        print "Read ".count($lines)." lines in ".strlen($txt)." bytes.\n";
        print "Extracting title...";
        $title = preg_replace("/^#\s*/", "", array_shift($lines));
        $parts = preg_split("/\:\s*/", $title, 2);

        
        print "Done.\nBlog title: \"{$parts[0]}\"\nBlog subtitle: \"{$parts[1]}\"\n\n";

        print "Grabbing comments...";
        if (file_exists("comments/$fparts[0].json")) {
            $comments = readComments("comments/$fparts[0].json");
        }

        print "Done. \n\nCreating new blog object...";
        $out = new stdClass();
        $out->fulltitle = $title;
        $out->title = $parts[0];
        $out->subtitle = $parts[1];
        $out->link = "/crblog/blog/".$fparts[0].".html";
        $out->name = strtolower(preg_replace("/\W/", '', $out->title));
        $out->date = date("Y-m-d");
        $out->tags = "";
        $out->target = "iframe";
        $out->hero = "/crblog/assets/img/".$fparts[0].".jpg";
        $out->icon = "fas fa-code";
        $out->blurb = $para[1];
        $out->comments = $comments;

        print "Done.\n\n";
        $done = (property_exists($conf, "notty")) ? 1 : 0;
        
        while (!$done) {
            $keys = array();
            $vals = array();
            print "Review:\n===========================\nNew blog object:\n";
            $i = 0;
            foreach ($out as $key=>$val) {
                $keys[] = $key;
                $vals[] = $val;
                ++$i;
                if (strlen($val)> 50) {
                    $val = substr($val, 0, 50)."...";
                }
                print "\t{$i}) $key:\t$val\n";
            }
            print "\nPlease review new blog entry for correctness.\nType a number or property to change its value.\nPress Enter when satified.\n";

            print "Enter or 'ok' to continue / # to edit: ";
            $input = getInput();

            if (preg_match("/\d/", $input)) {
                print "\n\nEditing value for {$keys[(int)$input-1]}\nOld value: {$vals[(int)$input-1]}\nNew value (enter nothing to cancel)? ";
                $newval = getInput();
                if ($newval) {
                    $out->{$vals[(int)$input-1]} = $newval;
                }
            } else if (($input == "")  || ($input=="ok"))  {
                $done = 1;
                continue;
            } else {
                print "Oops.  Input[{$input}]\n";
            }

        }
        print "\nWriting cleaned up markdown to tmp.md...";
        file_put_contents("tmp.md", join("\n", $lines));
        print "Done.\nConverting markdown to html...";
        $out->blogpost = `pandoc --no-highlight -f markdown -t html5 tmp.md`;
        print "Done.\nRemoving tmp.md file...";
        //$exe = `rm tmp.md`;
        print "Done.\n\n";

        print "Generating Site HTML...";
        $html = preg_replace_callback("/%%([^%]*)%%/", function($match) {
            global $out;
            return isset($out->{$match[1]}) ? $out->{$match[1]} : "";
        }, $tpl);
        print "Done.\nGenerated ".strlen($html)." bytes of HTML.\n";
        print "\nSaving generated html as {$fparts[0]}.html...";
        file_put_contents($fparts[0].".html", $html);
        print "Done.\n";
            
        unset($out->blogpost);

        if (property_exists($conf, "nav")) {
            $exists = 0;
            foreach ($posts as $post) {
                if ($post->fulltitle == $title) {
                    $exists = 1;
                }
            }

            if (!property_exists($conf, "force") && $exists) {
                print "*** Error: Blog entry named \"$title\" already exists. Aborting...\n";
                exit;
            }
            array_unshift($posts, $out);
            print "Added post to top of main blog list.\n";
            print "Saving new blog list...";
            file_put_contents("posts.json", json_encode($posts, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
            print "Wrote ".strlen($html)." bytes to {$fparts[0]}.html\n";
            print "\nUpdating main site nav/blog.json...";
            
            $out2 = new stdClass();
            $out2->title = $out->title;
            $out2->subtitle = $out->subtitle;
            $out2->fulltitle = $out->fulltitle;
            $out2->link = $out->link;
            $out2->name = strtolower(preg_replace("/\W/", '', $out->title));
            $out2->target = "iframe";
            $out2->icon = "fas fa-code";
            
            print "Adding new blog post to top of blog.json...";
            array_unshift($nav, $out2);
            print "Done.\nBacking up current blog.json...";
            $exe = `cp ../nav/blog.json backup/blog.$now.json`;
            print "Done.\nblog.json saved to backup/blog.$now.json.\nWriting updated blog.json...";
            file_put_contents("../nav/blog.json", json_encode($nav, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT));
            print "Done.\n\n";

            print "Blog entry added. You should review the following files:\n\tposts.json\n\t../nav/blog.json\n\t$fparts[0].html\n\t../assets/img/$fparts[0].jpg\n\nBe sure to create or change the image $fparts[0].jpg\n";
        }
    
    }
}

function readComments($file) {
    $comments = json_decode(file_get_contents($file));
    $out = "";
    if (count($comments)) {
        $out = "<ul class='comments-list'>";

        foreach ($comments as $comment) {
            $out .= makeComment($comment);
        }

        $out .= "</ul>";

    }
    return $out;
}

function makeComment($comment, $lvl = 0) {
    if (property_exists($comment, "date")) {
        $comment->date = date("M j", strtotime($comment->date));
    }
    $out = <<<EOT
<li class='comment-item' data-key='{$comment->_id}' data-parentid='{$comment->_parent}'>
    <div class='comment-head'>
        <div class='commenter'>{$comment->name}</div><div class='comment-date'>{$comment->date}</div>
    </div>
    <p class='comment'>{$comment->comment}</p>
EOT;
    if ($lvl < 3) {
        $out .= <<< EOT
<div class='reply-wrap'><span class='comment-tools'></span> <a class='reply-link' href='#' onclick='app.reply(this, event, "{$comment->_id}");return false'>Reply →</a></div>
EOT;

    }

    if (property_exists($comment, "replies")) {
        $out .= "\n<ul class='comment-reply'>";
        foreach ($comment->replies as $reply) {
            $out .= makeComment($reply, $lvl + 1);
        }
        $out .= "</ul>";
    }
    $out .= "</li>";
    return $out;
}
function getInput() {
    $handle = fopen ("php://stdin","r");
    $line = fgets($handle);
    $line = trim($line);
    fclose($handle);
    return $line;
}
?>
